version: "3.9"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    labels:
      - "coolify.managed=true"
      - "traefik.enable=false"
    volumes:
      - mongo_data:/data/db
      - mongo_logs:/var/log/mongodb/
    # No ports or expose needed for internal DB
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    command: [ '--logpath', '/var/log/mongodb/mongod.log' ]

  internal-translate:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    labels:
      - "coolify.managed=true"
      - "traefik.enable=false"
    # No ports or expose needed for internal service
    volumes:
      - libretranslate_data:/home/libretranslate/.local/share
      - libretranslate_cache:/home/libretranslate/.local/cache
    environment:
      LT_DISABLE_WEB_UI: "True"
      LT_UPDATE_MODELS: "True"
      LT_LOAD_ONLY: ${LT_LOAD_ONLY:-en,es,fr,ru}

  scriptus-app:
    build: .
    restart: unless-stopped
    expose:
      - 80
    healthcheck:
      test: [ "CMD-SHELL", "curl -4 -f -s -o /dev/null http://127.0.0.1/health-check || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    labels:
      - "coolify.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.scriptus-app.rule=Host(`scriptus.online`) || Host(`www.scriptus.online`)"
      - "traefik.http.routers.scriptus-app.priority=10000"
      - "traefik.http.services.scriptus-app.loadbalancer.server.port=80"

    volumes:
      - uploads:/app/uploads
      - models:/app/models
      - whishper_logs:/var/log/whishper
    depends_on:
      - mongo
      - internal-translate
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_ENDPOINT: mongo:27017
      ORIGIN: ${WHISHPER_HOST}
      PORT: "3000"
      ADDRESS: 0.0.0.0
      PROTOCOL_HEADER: x-forwarded-proto
      PUBLIC_INTERNAL_API_HOST: "http://127.0.0.1:8080"
      PUBLIC_TRANSLATION_API_HOST: ""
      PUBLIC_API_HOST: ${WHISHPER_HOST}
      UPLOAD_DIR: /app/uploads
      WHISPER_DEVICE: ${WHISPER_DEVICE}
      WHISPER_COMPUTE_TYPE: ${WHISPER_COMPUTE_TYPE}
      WHISPER_MODELS_DIR: ${WHISPER_MODELS_DIR}
      CPU_THREADS: ${CPU_THREADS}
      PUBLIC_WHISHPER_PROFILE: ${PUBLIC_WHISHPER_PROFILE}
      GROQ_API_KEY: ${GROQ_API_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      PUBLIC_SUPABASE_URL: ${SUPABASE_URL}
      PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}

volumes:
  mongo_data:
  mongo_logs:
  libretranslate_data:
  libretranslate_cache:
  uploads:
  models:
  whishper_logs:


